/**
 * Seeds public holidays into Turso production database
 * Run with: npx tsx scripts/seed-holidays-turso.ts
 */
import { readFileSync } from "fs";
import { PrismaClient } from "@prisma/client";
import { PrismaLibSQL } from "@prisma/adapter-libsql";

const envContent = readFileSync(".env", "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((line) => {
  const match = line.match(/^(\w+)\s*=\s*"(.+)"$/);
  if (match) env[match[1]] = match[2].trim();
});

const tursoUrl = env.TURSO_DATABASE_URL;
const tursoToken = env.TURSO_AUTH_TOKEN;

if (!tursoUrl || !tursoToken) {
  console.error("❌ Missing TURSO_DATABASE_URL or TURSO_AUTH_TOKEN in .env");
  process.exit(1);
}

const prisma = new PrismaClient({
  adapter: new PrismaLibSQL({ url: tursoUrl, authToken: tursoToken }),
});

interface HolidayData {
  countryCode: string;
  holidays: {
    name: string;
    localName?: string;
    date: string;
    type?: string;
    description?: string;
  }[];
}

const holidaysData: HolidayData[] = [
  {
    countryCode: "US",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", description: "Celebrates the beginning of the Gregorian calendar year" },
      { name: "Martin Luther King Jr. Day", date: "01-15", type: "public", description: "Honors the civil rights leader (third Monday in January)" },
      { name: "Presidents' Day", date: "02-19", type: "public", description: "Honors all U.S. presidents (third Monday in February)" },
      { name: "Memorial Day", date: "05-27", type: "public", description: "Honors military personnel who died in service (last Monday in May)" },
      { name: "Juneteenth", date: "06-19", type: "public", description: "Commemorates the end of slavery in the U.S." },
      { name: "Independence Day", date: "07-04", type: "public", description: "Celebrates the adoption of the Declaration of Independence" },
      { name: "Labor Day", date: "09-02", type: "public", description: "Celebrates the labor movement (first Monday in September)" },
      { name: "Columbus Day", date: "10-14", type: "public", description: "Honors Christopher Columbus (second Monday in October)" },
      { name: "Veterans Day", date: "11-11", type: "public", description: "Honors military veterans" },
      { name: "Thanksgiving Day", date: "11-28", type: "public", description: "Day of giving thanks (fourth Thursday in November)" },
      { name: "Christmas Day", date: "12-25", type: "public", description: "Celebrates the birth of Jesus Christ" },
    ],
  },
  {
    countryCode: "GB",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Early May Bank Holiday", date: "05-06", type: "public" },
      { name: "Spring Bank Holiday", date: "05-27", type: "public" },
      { name: "Summer Bank Holiday", date: "08-26", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "IN",
    holidays: [
      { name: "Republic Day", date: "01-26", type: "public", localName: "गणतंत्र दिवस" },
      { name: "Independence Day", date: "08-15", type: "public", localName: "स्वतंत्रता दिवस" },
      { name: "Gandhi Jayanti", date: "10-02", type: "public", localName: "गांधी जयंती" },
      { name: "Diwali", date: "11-01", type: "public", localName: "दीपावली" },
      { name: "Holi", date: "03-25", type: "public", localName: "होली" },
      { name: "Eid al-Fitr", date: "04-10", type: "public", localName: "ईद उल-फित्र" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "AU",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Australia Day", date: "01-26", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Anzac Day", date: "04-25", type: "public" },
      { name: "Queen's Birthday", date: "06-10", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "JP",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "元日" },
      { name: "Coming of Age Day", date: "01-08", type: "public", localName: "成人の日" },
      { name: "National Foundation Day", date: "02-11", type: "public", localName: "建国記念の日" },
      { name: "Vernal Equinox Day", date: "03-20", type: "public", localName: "春分の日" },
      { name: "Showa Day", date: "04-29", type: "public", localName: "昭和の日" },
      { name: "Constitution Memorial Day", date: "05-03", type: "public", localName: "憲法記念日" },
      { name: "Greenery Day", date: "05-04", type: "public", localName: "みどりの日" },
      { name: "Children's Day", date: "05-05", type: "public", localName: "こどもの日" },
      { name: "Marine Day", date: "07-15", type: "public", localName: "海の日" },
      { name: "Mountain Day", date: "08-11", type: "public", localName: "山の日" },
      { name: "Respect for the Aged Day", date: "09-16", type: "public", localName: "敬老の日" },
      { name: "Autumnal Equinox Day", date: "09-22", type: "public", localName: "秋分の日" },
      { name: "Sports Day", date: "10-14", type: "public", localName: "スポーツの日" },
      { name: "Culture Day", date: "11-03", type: "public", localName: "文化の日" },
      { name: "Labor Thanksgiving Day", date: "11-23", type: "public", localName: "勤労感謝の日" },
    ],
  },
  {
    countryCode: "DE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Neujahr" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Karfreitag" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Ostermontag" },
      { name: "Labor Day", date: "05-01", type: "public", localName: "Tag der Arbeit" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Christi Himmelfahrt" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pfingstmontag" },
      { name: "German Unity Day", date: "10-03", type: "public", localName: "Tag der Deutschen Einheit" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Erster Weihnachtstag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Zweiter Weihnachtstag" },
    ],
  },
  {
    countryCode: "FR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Jour de l'An" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Lundi de Pâques" },
      { name: "Labor Day", date: "05-01", type: "public", localName: "Fête du Travail" },
      { name: "Victory in Europe Day", date: "05-08", type: "public", localName: "Victoire 1945" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Ascension" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pentecôte" },
      { name: "Bastille Day", date: "07-14", type: "public", localName: "Fête nationale" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Assomption" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Toussaint" },
      { name: "Armistice Day", date: "11-11", type: "public", localName: "Armistice" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Noël" },
    ],
  },
  {
    countryCode: "CA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Family Day", date: "02-19", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Victoria Day", date: "05-20", type: "public" },
      { name: "Canada Day", date: "07-01", type: "public" },
      { name: "Civic Holiday", date: "08-05", type: "public" },
      { name: "Labor Day", date: "09-02", type: "public" },
      { name: "Thanksgiving Day", date: "10-14", type: "public" },
      { name: "Remembrance Day", date: "11-11", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "CN",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "元旦" },
      { name: "Chinese New Year", date: "02-10", type: "public", localName: "春节" },
      { name: "Qingming Festival", date: "04-04", type: "public", localName: "清明节" },
      { name: "Labor Day", date: "05-01", type: "public", localName: "劳动节" },
      { name: "Dragon Boat Festival", date: "06-10", type: "public", localName: "端午节" },
      { name: "Mid-Autumn Festival", date: "09-17", type: "public", localName: "中秋节" },
      { name: "National Day", date: "10-01", type: "public", localName: "国庆节" },
    ],
  },
  {
    countryCode: "BR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Ano Novo" },
      { name: "Carnival", date: "02-12", type: "public", localName: "Carnaval" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Sexta-feira Santa" },
      { name: "Tiradentes Day", date: "04-21", type: "public", localName: "Dia de Tiradentes" },
      { name: "Labor Day", date: "05-01", type: "public", localName: "Dia do Trabalho" },
      { name: "Independence Day", date: "09-07", type: "public", localName: "Dia da Independência" },
      { name: "Our Lady of Aparecida", date: "10-12", type: "public", localName: "Nossa Senhora Aparecida" },
      { name: "All Souls' Day", date: "11-02", type: "public", localName: "Dia de Finados" },
      { name: "Republic Day", date: "11-15", type: "public", localName: "Dia da República" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Natal" },
    ],
  },
  {
    countryCode: "SG",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Chinese New Year", date: "02-10", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Hari Raya Puasa", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Vesak Day", date: "05-22", type: "public" },
      { name: "Hari Raya Haji", date: "06-17", type: "public" },
      { name: "National Day", date: "08-09", type: "public" },
      { name: "Deepavali", date: "10-31", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "AE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Arafat Day", date: "06-16", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Prophet Muhammad's Birthday", date: "09-15", type: "public" },
      { name: "Commemoration Day", date: "11-30", type: "public" },
      { name: "National Day", date: "12-02", type: "public" },
    ],
  },
  {
    countryCode: "RU",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Новый год" },
      { name: "Orthodox Christmas", date: "01-07", type: "public", localName: "Рождество Христово" },
      { name: "Defender of the Fatherland Day", date: "02-23", type: "public", localName: "День защитника Отечества" },
      { name: "International Women's Day", date: "03-08", type: "public", localName: "Международный женский день" },
      { name: "Spring and Labour Day", date: "05-01", type: "public", localName: "Праздник Весны и Труда" },
      { name: "Victory Day", date: "05-09", type: "public", localName: "День Победы" },
      { name: "Russia Day", date: "06-12", type: "public", localName: "День России" },
      { name: "Unity Day", date: "11-04", type: "public", localName: "День народного единства" },
    ],
  },
  {
    countryCode: "KR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "신정" },
      { name: "Seollal", date: "02-10", type: "public", localName: "설날" },
      { name: "Independence Movement Day", date: "03-01", type: "public", localName: "삼일절" },
      { name: "Children's Day", date: "05-05", type: "public", localName: "어린이날" },
      { name: "Buddha's Birthday", date: "05-15", type: "public", localName: "부처님 오신 날" },
      { name: "Memorial Day", date: "06-06", type: "public", localName: "현충일" },
      { name: "Liberation Day", date: "08-15", type: "public", localName: "광복절" },
      { name: "Chuseok", date: "09-17", type: "public", localName: "추석" },
      { name: "National Foundation Day", date: "10-03", type: "public", localName: "개천절" },
      { name: "Hangul Day", date: "10-09", type: "public", localName: "한글날" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "크리스마스" },
    ],
  },
  {
    countryCode: "MX",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Constitution Day", date: "02-05", type: "public", localName: "Día de la Constitución" },
      { name: "Benito Juárez's Birthday", date: "03-18", type: "public", localName: "Natalicio de Benito Juárez" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajo" },
      { name: "Independence Day", date: "09-16", type: "public", localName: "Día de la Independencia" },
      { name: "Day of the Dead", date: "11-02", type: "public", localName: "Día de los Muertos" },
      { name: "Revolution Day", date: "11-20", type: "public", localName: "Día de la Revolución" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "IT",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Capodanno" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Epifania" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Lunedì dell'Angelo" },
      { name: "Liberation Day", date: "04-25", type: "public", localName: "Festa della Liberazione" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Festa dei Lavoratori" },
      { name: "Republic Day", date: "06-02", type: "public", localName: "Festa della Repubblica" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Ferragosto" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Tutti i Santi" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Immacolata Concezione" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Natale" },
      { name: "St. Stephen's Day", date: "12-26", type: "public", localName: "Santo Stefano" },
    ],
  },
  {
    countryCode: "ES",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Día de los Reyes Magos" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajador" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Asunción de la Virgen" },
      { name: "National Day", date: "10-12", type: "public", localName: "Fiesta Nacional de España" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Día de Todos los Santos" },
      { name: "Constitution Day", date: "12-06", type: "public", localName: "Día de la Constitución" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Inmaculada Concepción" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "NL",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nieuwjaarsdag" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Goede Vrijdag" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Tweede Paasdag" },
      { name: "King's Day", date: "04-27", type: "public", localName: "Koningsdag" },
      { name: "Liberation Day", date: "05-05", type: "public", localName: "Bevrijdingsdag" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Hemelvaartsdag" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Tweede Pinksterdag" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Eerste Kerstdag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Tweede Kerstdag" },
    ],
  },
  {
    countryCode: "CH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Neujahrstag" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Karfreitag" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Ostermontag" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Auffahrt" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pfingstmontag" },
      { name: "National Day", date: "08-01", type: "public", localName: "Bundesfeier" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Weihnachtstag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Stephanstag" },
    ],
  },
  {
    countryCode: "SE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nyårsdagen" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Trettondedag jul" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Långfredagen" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Annandag påsk" },
      { name: "May Day", date: "05-01", type: "public", localName: "Första maj" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Kristi himmelsfärdsdag" },
      { name: "National Day", date: "06-06", type: "public", localName: "Sveriges nationaldag" },
      { name: "Midsummer Eve", date: "06-21", type: "public", localName: "Midsommarafton" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Juldagen" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Annandag jul" },
    ],
  },
  {
    countryCode: "NZ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Day after New Year", date: "01-02", type: "public" },
      { name: "Waitangi Day", date: "02-06", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Anzac Day", date: "04-25", type: "public" },
      { name: "King's Birthday", date: "06-03", type: "public" },
      { name: "Matariki", date: "06-28", type: "public" },
      { name: "Labour Day", date: "10-28", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "IE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "St. Patrick's Day", date: "03-17", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "May Day", date: "05-06", type: "public" },
      { name: "June Bank Holiday", date: "06-03", type: "public" },
      { name: "August Bank Holiday", date: "08-05", type: "public" },
      { name: "October Bank Holiday", date: "10-28", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "St. Stephen's Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "ZA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Human Rights Day", date: "03-21", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Family Day", date: "04-01", type: "public" },
      { name: "Freedom Day", date: "04-27", type: "public" },
      { name: "Workers' Day", date: "05-01", type: "public" },
      { name: "Youth Day", date: "06-16", type: "public" },
      { name: "National Women's Day", date: "08-09", type: "public" },
      { name: "Heritage Day", date: "09-24", type: "public" },
      { name: "Day of Reconciliation", date: "12-16", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Day of Goodwill", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "TR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Yılbaşı" },
      { name: "Ramadan Feast", date: "04-10", type: "public", localName: "Ramazan Bayramı" },
      { name: "National Sovereignty and Children's Day", date: "04-23", type: "public", localName: "Ulusal Egemenlik ve Çocuk Bayramı" },
      { name: "Labour and Solidarity Day", date: "05-01", type: "public", localName: "Emek ve Dayanışma Günü" },
      { name: "Commemoration of Atatürk, Youth and Sports Day", date: "05-19", type: "public", localName: "Atatürk'ü Anma, Gençlik ve Spor Bayramı" },
      { name: "Sacrifice Feast", date: "06-17", type: "public", localName: "Kurban Bayramı" },
      { name: "Democracy and National Unity Day", date: "07-15", type: "public", localName: "Demokrasi ve Milli Birlik Günü" },
      { name: "Victory Day", date: "08-30", type: "public", localName: "Zafer Bayramı" },
      { name: "Republic Day", date: "10-29", type: "public", localName: "Cumhuriyet Bayramı" },
    ],
  },
  {
    countryCode: "TH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "วันขึ้นปีใหม่" },
      { name: "Makha Bucha Day", date: "02-24", type: "public", localName: "วันมาฆบูชา" },
      { name: "Chakri Memorial Day", date: "04-06", type: "public", localName: "วันจักรี" },
      { name: "Songkran Festival", date: "04-13", type: "public", localName: "วันสงกรานต์" },
      { name: "Coronation Day", date: "05-04", type: "public", localName: "วันฉัตรมงคล" },
      { name: "Visakha Bucha Day", date: "05-22", type: "public", localName: "วันวิสาขบูชา" },
      { name: "HM King's Birthday", date: "07-28", type: "public", localName: "วันเฉลิมพระชนมพรรษา" },
      { name: "HM Queen Mother's Birthday", date: "08-12", type: "public", localName: "วันเฉลิมพระชนมพรรษาสมเด็จพระบรมราชชนนีพันปีหลวง" },
      { name: "King Bhumibol Memorial Day", date: "10-13", type: "public", localName: "วันคล้ายวันสวรรคต" },
      { name: "Chulalongkorn Day", date: "10-23", type: "public", localName: "วันปิยมหาราช" },
      { name: "HM King's Birthday (Father's Day)", date: "12-05", type: "public", localName: "วันพ่อแห่งชาติ" },
      { name: "Constitution Day", date: "12-10", type: "public", localName: "วันรัฐธรรมนูญ" },
      { name: "New Year's Eve", date: "12-31", type: "public", localName: "วันสิ้นปี" },
    ],
  },
  {
    countryCode: "EG",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Coptic Christmas", date: "01-07", type: "public" },
      { name: "Revolution Day (Jan 25)", date: "01-25", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Sinai Liberation Day", date: "04-25", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Sham El Nessim", date: "05-06", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Revolution Day (Jul 23)", date: "07-23", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Armed Forces Day", date: "10-06", type: "public" },
      { name: "Prophet Muhammad's Birthday", date: "09-15", type: "public" },
    ],
  },
  {
    countryCode: "AR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Carnival", date: "02-12", type: "public", localName: "Carnaval" },
      { name: "Truth and Justice Memorial Day", date: "03-24", type: "public", localName: "Día de la Memoria" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Malvinas Day", date: "04-02", type: "public", localName: "Día del Veterano de Malvinas" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajador" },
      { name: "May Revolution", date: "05-25", type: "public", localName: "Día de la Revolución de Mayo" },
      { name: "Independence Day", date: "07-09", type: "public", localName: "Día de la Independencia" },
      { name: "San Martín Day", date: "08-17", type: "public", localName: "Día del Libertador San Martín" },
      { name: "Day of Respect for Cultural Diversity", date: "10-12", type: "public", localName: "Día del Respeto a la Diversidad Cultural" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "PT",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Ano Novo" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Sexta-feira Santa" },
      { name: "Easter Sunday", date: "03-31", type: "public", localName: "Páscoa" },
      { name: "Liberty Day", date: "04-25", type: "public", localName: "Dia da Liberdade" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Dia do Trabalhador" },
      { name: "Portugal Day", date: "06-10", type: "public", localName: "Dia de Portugal" },
      { name: "Corpus Christi", date: "05-30", type: "public", localName: "Corpo de Deus" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Assunção de Nossa Senhora" },
      { name: "Republic Day", date: "10-05", type: "public", localName: "Implantação da República" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Dia de Todos os Santos" },
      { name: "Restoration of Independence", date: "12-01", type: "public", localName: "Restauração da Independência" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Imaculada Conceição" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Natal" },
    ],
  },
  {
    countryCode: "PL",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nowy Rok" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Święto Trzech Króli" },
      { name: "Easter Sunday", date: "03-31", type: "public", localName: "Wielkanoc" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Poniedziałek Wielkanocny" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Święto Pracy" },
      { name: "Constitution Day", date: "05-03", type: "public", localName: "Święto Konstytucji 3 Maja" },
      { name: "Corpus Christi", date: "05-30", type: "public", localName: "Boże Ciało" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Wniebowzięcie NMP" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Wszystkich Świętych" },
      { name: "Independence Day", date: "11-11", type: "public", localName: "Narodowe Święto Niepodległości" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Boże Narodzenie" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Drugi dzień Bożego Narodzenia" },
    ],
  },
  {
    countryCode: "GR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Πρωτοχρονιά" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Θεοφάνεια" },
      { name: "Clean Monday", date: "03-18", type: "public", localName: "Καθαρά Δευτέρα" },
      { name: "Independence Day", date: "03-25", type: "public", localName: "Ευαγγελισμός της Θεοτόκου" },
      { name: "Good Friday", date: "05-03", type: "public", localName: "Μεγάλη Παρασκευή" },
      { name: "Easter Monday", date: "05-06", type: "public", localName: "Δευτέρα του Πάσχα" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Εργατική Πρωτομαγιά" },
      { name: "Holy Spirit Monday", date: "06-24", type: "public", localName: "Αγίου Πνεύματος" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Κοίμηση της Θεοτόκου" },
      { name: "Ohi Day", date: "10-28", type: "public", localName: "Επέτειος του Όχι" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Χριστούγεννα" },
    ],
  },
  {
    countryCode: "IL",
    holidays: [
      { name: "Purim", date: "03-24", type: "public", localName: "פורים" },
      { name: "Passover", date: "04-23", type: "public", localName: "פסח" },
      { name: "Independence Day", date: "05-14", type: "public", localName: "יום העצמאות" },
      { name: "Shavuot", date: "06-12", type: "public", localName: "שבועות" },
      { name: "Rosh Hashanah", date: "10-03", type: "public", localName: "ראש השנה" },
      { name: "Yom Kippur", date: "10-12", type: "public", localName: "יום כיפור" },
      { name: "Sukkot", date: "10-17", type: "public", localName: "סוכות" },
      { name: "Simchat Torah", date: "10-25", type: "public", localName: "שמחת תורה" },
    ],
  },
  {
    countryCode: "SA",
    holidays: [
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Saudi National Day", date: "09-23", type: "public" },
    ],
  },
  {
    countryCode: "ID",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Tahun Baru Masehi" },
      { name: "Isra Miraj", date: "02-08", type: "public", localName: "Isra Mikraj" },
      { name: "Nyepi", date: "03-11", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public", localName: "Idul Fitri" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Vesak Day", date: "05-23", type: "public", localName: "Waisak" },
      { name: "Ascension of Jesus", date: "05-09", type: "public", localName: "Kenaikan Isa Almasih" },
      { name: "Pancasila Day", date: "06-01", type: "public", localName: "Hari Lahir Pancasila" },
      { name: "Eid al-Adha", date: "06-17", type: "public", localName: "Idul Adha" },
      { name: "Islamic New Year", date: "07-07", type: "public", localName: "Tahun Baru Islam" },
      { name: "Independence Day", date: "08-17", type: "public", localName: "Hari Kemerdekaan" },
      { name: "Prophet Muhammad's Birthday", date: "09-15", type: "public", localName: "Maulid Nabi" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Hari Natal" },
    ],
  },
  {
    countryCode: "MY",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Chinese New Year", date: "02-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Wesak Day", date: "05-22", type: "public" },
      { name: "Agong's Birthday", date: "06-03", type: "public" },
      { name: "Hari Raya Puasa", date: "04-10", type: "public" },
      { name: "Hari Raya Haji", date: "06-17", type: "public" },
      { name: "National Day", date: "08-31", type: "public", localName: "Hari Merdeka" },
      { name: "Malaysia Day", date: "09-16", type: "public" },
      { name: "Deepavali", date: "10-31", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "VN",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Tết Dương lịch" },
      { name: "Tet Holiday", date: "02-10", type: "public", localName: "Tết Nguyên Đán" },
      { name: "Hung Kings Commemoration", date: "04-18", type: "public", localName: "Giỗ Tổ Hùng Vương" },
      { name: "Reunification Day", date: "04-30", type: "public", localName: "Ngày Thống nhất" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Ngày Quốc tế Lao động" },
      { name: "National Day", date: "09-02", type: "public", localName: "Quốc khánh" },
    ],
  },
  {
    countryCode: "PH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Maundy Thursday", date: "03-28", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Araw ng Kagitingan", date: "04-09", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Independence Day", date: "06-12", type: "public" },
      { name: "National Heroes Day", date: "08-26", type: "public" },
      { name: "Bonifacio Day", date: "11-30", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Rizal Day", date: "12-30", type: "public" },
    ],
  },
  {
    countryCode: "PK",
    holidays: [
      { name: "Kashmir Solidarity Day", date: "02-05", type: "public" },
      { name: "Pakistan Day", date: "03-23", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Independence Day", date: "08-14", type: "public" },
      { name: "Ashura", date: "07-17", type: "public" },
      { name: "Eid Milad un-Nabi", date: "09-15", type: "public" },
      { name: "Iqbal Day", date: "11-09", type: "public" },
      { name: "Quaid-e-Azam Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "AT",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Neujahr" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Heilige Drei Könige" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Ostermontag" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Staatsfeiertag" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Christi Himmelfahrt" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pfingstmontag" },
      { name: "Corpus Christi", date: "05-30", type: "public", localName: "Fronleichnam" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Mariä Himmelfahrt" },
      { name: "National Day", date: "10-26", type: "public", localName: "Nationalfeiertag" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Allerheiligen" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Mariä Empfängnis" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Christtag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Stefanitag" },
    ],
  },
  {
    countryCode: "BE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nieuwjaar" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Paasmaandag" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Dag van de Arbeid" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Onze Lieve Heer Hemelvaart" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pinkstermaandag" },
      { name: "National Day", date: "07-21", type: "public", localName: "Nationale Feestdag" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Onze Lieve Vrouw Hemelvaart" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Allerheiligen" },
      { name: "Armistice Day", date: "11-11", type: "public", localName: "Wapenstilstand" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Kerstmis" },
    ],
  },
  {
    countryCode: "DK",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nytårsdag" },
      { name: "Maundy Thursday", date: "03-28", type: "public", localName: "Skærtorsdag" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Langfredag" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Anden påskedag" },
      { name: "Prayer Day", date: "04-26", type: "public", localName: "Store Bededag" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Kristi Himmelfartsdag" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Anden pinsedag" },
      { name: "Constitution Day", date: "06-05", type: "public", localName: "Grundlovsdag" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Juledag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Anden juledag" },
    ],
  },
  {
    countryCode: "FI",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Uudenvuodenpäivä" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Loppiainen" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Pitkäperjantai" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "2. pääsiäispäivä" },
      { name: "May Day", date: "05-01", type: "public", localName: "Vappu" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Helatorstai" },
      { name: "Midsummer Eve", date: "06-21", type: "public", localName: "Juhannusaatto" },
      { name: "All Saints' Day", date: "11-02", type: "public", localName: "Pyhäinpäivä" },
      { name: "Independence Day", date: "12-06", type: "public", localName: "Itsenäisyyspäivä" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Joulupäivä" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Tapaninpäivä" },
    ],
  },
  {
    countryCode: "NO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Første nyttårsdag" },
      { name: "Maundy Thursday", date: "03-28", type: "public", localName: "Skjærtorsdag" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Langfredag" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Andre påskedag" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Arbeidernes dag" },
      { name: "Constitution Day", date: "05-17", type: "public", localName: "Grunnlovsdagen" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Kristi himmelfartsdag" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Andre pinsedag" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Første juledag" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Andre juledag" },
    ],
  },
  {
    countryCode: "CZ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nový rok" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Velký pátek" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Velikonoční pondělí" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Svátek práce" },
      { name: "Liberation Day", date: "05-08", type: "public", localName: "Den vítězství" },
      { name: "St. Cyril and Methodius Day", date: "07-05", type: "public", localName: "Den slovanských věrozvěstů" },
      { name: "Jan Hus Day", date: "07-06", type: "public", localName: "Den upálení mistra Jana Husa" },
      { name: "St. Wenceslas Day", date: "09-28", type: "public", localName: "Den české státnosti" },
      { name: "Independent State Day", date: "10-28", type: "public", localName: "Den vzniku samostatného československého státu" },
      { name: "Freedom and Democracy Day", date: "11-17", type: "public", localName: "Den boje za svobodu a demokracii" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Štědrý den" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "1. svátek vánoční" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "2. svátek vánoční" },
    ],
  },
  {
    countryCode: "HU",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Újév" },
      { name: "Revolution Day", date: "03-15", type: "public", localName: "Nemzeti ünnep" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Nagypéntek" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Húsvéthétfő" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "A munka ünnepe" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Pünkösdhétfő" },
      { name: "State Foundation Day", date: "08-20", type: "public", localName: "Az államalapítás ünnepe" },
      { name: "Republic Day", date: "10-23", type: "public", localName: "Nemzeti ünnep" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Mindenszentek" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Karácsony" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Karácsony másnapja" },
    ],
  },
  {
    countryCode: "RO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Anul Nou" },
      { name: "Union Day", date: "01-24", type: "public", localName: "Ziua Unirii" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Vinerea Mare" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "A doua zi de Paște" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Ziua Muncii" },
      { name: "Children's Day", date: "06-01", type: "public", localName: "Ziua Copilului" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "A doua zi de Rusalii" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Adormirea Maicii Domnului" },
      { name: "St. Andrew's Day", date: "11-30", type: "public", localName: "Sfântul Andrei" },
      { name: "National Day", date: "12-01", type: "public", localName: "Ziua Națională" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Crăciunul" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "A doua zi de Crăciun" },
    ],
  },
  {
    countryCode: "UA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Новий Рік" },
      { name: "Orthodox Christmas", date: "01-07", type: "public", localName: "Різдво Христове" },
      { name: "Women's Day", date: "03-08", type: "public", localName: "Міжнародний жіночий день" },
      { name: "Easter Sunday", date: "05-05", type: "public", localName: "Великдень" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "День праці" },
      { name: "Victory Day", date: "05-09", type: "public", localName: "День перемоги" },
      { name: "Constitution Day", date: "06-28", type: "public", localName: "День Конституції" },
      { name: "Independence Day", date: "08-24", type: "public", localName: "День Незалежності" },
      { name: "Defender Day", date: "10-14", type: "public", localName: "День захисника України" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "NG",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Workers' Day", date: "05-01", type: "public" },
      { name: "Democracy Day", date: "06-12", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Independence Day", date: "10-01", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "KE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Madaraka Day", date: "06-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Mashujaa Day", date: "10-20", type: "public" },
      { name: "Jamhuri Day", date: "12-12", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "CO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Día de los Reyes Magos" },
      { name: "St. Joseph's Day", date: "03-19", type: "public", localName: "Día de San José" },
      { name: "Maundy Thursday", date: "03-28", type: "public", localName: "Jueves Santo" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajo" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Ascensión del Señor" },
      { name: "Corpus Christi", date: "05-30", type: "public", localName: "Corpus Christi" },
      { name: "Sacred Heart", date: "06-07", type: "public", localName: "Sagrado Corazón" },
      { name: "Independence Day", date: "07-20", type: "public", localName: "Día de la Independencia" },
      { name: "Battle of Boyacá", date: "08-07", type: "public", localName: "Batalla de Boyacá" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Asunción de la Virgen" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Día de Todos los Santos" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Inmaculada Concepción" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "CL",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Easter Saturday", date: "03-30", type: "public", localName: "Sábado Santo" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajador" },
      { name: "Navy Day", date: "05-21", type: "public", localName: "Día de las Glorias Navales" },
      { name: "St. Peter and St. Paul", date: "06-29", type: "public", localName: "San Pedro y San Pablo" },
      { name: "Our Lady of Mount Carmel", date: "07-16", type: "public", localName: "Virgen del Carmen" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Asunción de la Virgen" },
      { name: "Independence Day", date: "09-18", type: "public", localName: "Fiestas Patrias" },
      { name: "Army Day", date: "09-19", type: "public", localName: "Día de las Glorias del Ejército" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Día de Todos los Santos" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Inmaculada Concepción" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "PE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Año Nuevo" },
      { name: "Maundy Thursday", date: "03-28", type: "public", localName: "Jueves Santo" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Viernes Santo" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Día del Trabajo" },
      { name: "St. Peter and St. Paul", date: "06-29", type: "public", localName: "San Pedro y San Pablo" },
      { name: "Independence Day", date: "07-28", type: "public", localName: "Fiestas Patrias" },
      { name: "Santa Rosa de Lima", date: "08-30", type: "public", localName: "Día de Santa Rosa de Lima" },
      { name: "Battle of Angamos", date: "10-08", type: "public", localName: "Combate de Angamos" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Día de Todos los Santos" },
      { name: "Immaculate Conception", date: "12-08", type: "public", localName: "Inmaculada Concepción" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Navidad" },
    ],
  },
  {
    countryCode: "TW",
    holidays: [
      { name: "Republic Day", date: "01-01", type: "public", localName: "開國紀念日" },
      { name: "Chinese New Year", date: "02-10", type: "public", localName: "春節" },
      { name: "Peace Memorial Day", date: "02-28", type: "public", localName: "和平紀念日" },
      { name: "Children's Day", date: "04-04", type: "public", localName: "兒童節" },
      { name: "Tomb Sweeping Day", date: "04-05", type: "public", localName: "清明節" },
      { name: "Dragon Boat Festival", date: "06-10", type: "public", localName: "端午節" },
      { name: "Mid-Autumn Festival", date: "09-17", type: "public", localName: "中秋節" },
      { name: "National Day", date: "10-10", type: "public", localName: "國慶日" },
    ],
  },
  {
    countryCode: "HK",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Chinese New Year", date: "02-10", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Ching Ming Festival", date: "04-04", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Buddha's Birthday", date: "05-15", type: "public" },
      { name: "Tuen Ng Festival", date: "06-10", type: "public" },
      { name: "HKSAR Establishment Day", date: "07-01", type: "public" },
      { name: "Mid-Autumn Festival", date: "09-17", type: "public" },
      { name: "National Day", date: "10-01", type: "public" },
      { name: "Chung Yeung Festival", date: "10-11", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "BD",
    holidays: [
      { name: "Language Martyrs' Day", date: "02-21", type: "public" },
      { name: "Independence Day", date: "03-26", type: "public" },
      { name: "Bengali New Year", date: "04-14", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "May Day", date: "05-01", type: "public" },
      { name: "Buddha Purnima", date: "05-23", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "National Mourning Day", date: "08-15", type: "public" },
      { name: "Durga Puja", date: "10-12", type: "public" },
      { name: "Victory Day", date: "12-16", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "NP",
    holidays: [
      { name: "Maghe Sankranti", date: "01-14", type: "public" },
      { name: "Maha Shivaratri", date: "02-26", type: "public" },
      { name: "Holi", date: "03-25", type: "public" },
      { name: "Nepali New Year", date: "04-14", type: "public" },
      { name: "Buddha Jayanti", date: "05-23", type: "public" },
      { name: "Constitution Day", date: "09-19", type: "public" },
      { name: "Dashain", date: "10-12", type: "public" },
      { name: "Tihar", date: "11-01", type: "public" },
      { name: "New Year's Day", date: "01-01", type: "public" },
    ],
  },
  {
    countryCode: "LK",
    holidays: [
      { name: "Tamil Thai Pongal", date: "01-14", type: "public" },
      { name: "Independence Day", date: "02-04", type: "public" },
      { name: "Sinhala and Tamil New Year", date: "04-14", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "May Day", date: "05-01", type: "public" },
      { name: "Vesak", date: "05-23", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Deepavali", date: "10-31", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "HR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nova godina" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Sveta tri kralja" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Uskrsni ponedjeljak" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Praznik rada" },
      { name: "Statehood Day", date: "05-30", type: "public", localName: "Dan državnosti" },
      { name: "Corpus Christi", date: "05-30", type: "public", localName: "Tijelovo" },
      { name: "Anti-Fascist Day", date: "06-22", type: "public", localName: "Dan antifašističke borbe" },
      { name: "Victory Day", date: "08-05", type: "public", localName: "Dan pobjede" },
      { name: "Assumption of Mary", date: "08-15", type: "public", localName: "Velika Gospa" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Dan svih svetih" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Božić" },
      { name: "St. Stephen's Day", date: "12-26", type: "public", localName: "Sveti Stjepan" },
    ],
  },
  {
    countryCode: "BG",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Нова година" },
      { name: "Liberation Day", date: "03-03", type: "public", localName: "Освобождение" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Разпети петък" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Великден" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Ден на труда" },
      { name: "St. George's Day", date: "05-06", type: "public", localName: "Гергьовден" },
      { name: "Culture Day", date: "05-24", type: "public", localName: "Просвета и култура" },
      { name: "Unification Day", date: "09-06", type: "public", localName: "Съединение" },
      { name: "Independence Day", date: "09-22", type: "public", localName: "Независимост" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Бъдни вечер" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Рождество" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "IS",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nýársdagur" },
      { name: "Maundy Thursday", date: "03-28", type: "public", localName: "Skírdagur" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Föstudaginn langi" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Annar í páskum" },
      { name: "First Day of Summer", date: "04-25", type: "public", localName: "Sumardagurinn fyrsti" },
      { name: "May Day", date: "05-01", type: "public", localName: "Verkalýðsdagurinn" },
      { name: "Ascension Day", date: "05-09", type: "public", localName: "Uppstigningardagur" },
      { name: "Whit Monday", date: "05-20", type: "public", localName: "Annar í hvítasunnu" },
      { name: "National Day", date: "06-17", type: "public", localName: "Þjóðhátíðardagurinn" },
      { name: "Commerce Day", date: "08-05", type: "public", localName: "Frídagur verslunarmanna" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Aðfangadagur" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Jóladagur" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Annar í jólum" },
    ],
  },
  {
    countryCode: "EE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Uusaasta" },
      { name: "Independence Day", date: "02-24", type: "public", localName: "Iseseisvuspäev" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Suur reede" },
      { name: "Easter Sunday", date: "03-31", type: "public", localName: "Ülestõusmispühade 1. püha" },
      { name: "Spring Day", date: "05-01", type: "public", localName: "Kevadpüha" },
      { name: "Whit Sunday", date: "05-19", type: "public", localName: "Nelipühade 1. püha" },
      { name: "Victory Day", date: "06-23", type: "public", localName: "Võidupüha" },
      { name: "Midsummer Day", date: "06-24", type: "public", localName: "Jaanipäev" },
      { name: "Restoration Day", date: "08-20", type: "public", localName: "Taasiseseisvumispäev" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Jõululaupäev" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Esimene jõulupüha" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Teine jõulupüha" },
    ],
  },
  {
    countryCode: "LV",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Jaungada diena" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Lielā Piektdiena" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Otrās Lieldienas" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Darba svētki" },
      { name: "Restoration Day", date: "05-04", type: "public", localName: "Neatkarības atjaunošanas diena" },
      { name: "Midsummer Eve", date: "06-23", type: "public", localName: "Līgo diena" },
      { name: "Midsummer Day", date: "06-24", type: "public", localName: "Jāņu diena" },
      { name: "Proclamation Day", date: "11-18", type: "public", localName: "Proklamēšanas diena" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Ziemassvētku vakars" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Ziemassvētki" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Otrie Ziemassvētki" },
    ],
  },
  {
    countryCode: "LT",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Naujieji metai" },
      { name: "Independence Day", date: "02-16", type: "public", localName: "Valstybės atkūrimo diena" },
      { name: "Restoration Day", date: "03-11", type: "public", localName: "Nepriklausomybės atkūrimo diena" },
      { name: "Easter Sunday", date: "03-31", type: "public", localName: "Velykos" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Antroji Velykų diena" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Tarptautinė darbo diena" },
      { name: "Midsummer Day", date: "06-24", type: "public", localName: "Joninės" },
      { name: "Statehood Day", date: "07-06", type: "public", localName: "Valstybės diena" },
      { name: "Assumption Day", date: "08-15", type: "public", localName: "Žolinė" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Visų šventųjų diena" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Kūčios" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Kalėdos" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "Antroji Kalėdų diena" },
    ],
  },
  {
    countryCode: "SK",
    holidays: [
      { name: "Republic Day", date: "01-01", type: "public", localName: "Deň vzniku SR" },
      { name: "Epiphany", date: "01-06", type: "public", localName: "Zjavenie Pána" },
      { name: "Good Friday", date: "03-29", type: "public", localName: "Veľký piatok" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Veľkonočný pondelok" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Sviatok práce" },
      { name: "Liberation Day", date: "05-08", type: "public", localName: "Deň víťazstva" },
      { name: "St. Cyril and Methodius", date: "07-05", type: "public", localName: "Sviatok Cyrila a Metoda" },
      { name: "Slovak Uprising", date: "08-29", type: "public", localName: "Výročie SNP" },
      { name: "Constitution Day", date: "09-01", type: "public", localName: "Deň Ústavy" },
      { name: "Our Lady of Sorrows", date: "09-15", type: "public", localName: "Sedembolestná Panna Mária" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Všetkých svätých" },
      { name: "Freedom Day", date: "11-17", type: "public", localName: "Deň boja za slobodu" },
      { name: "Christmas Eve", date: "12-24", type: "public", localName: "Štedrý deň" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "1. sviatok vianočný" },
      { name: "Boxing Day", date: "12-26", type: "public", localName: "2. sviatok vianočný" },
    ],
  },
  {
    countryCode: "SI",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Novo leto" },
      { name: "Prešeren Day", date: "02-08", type: "public", localName: "Prešernov dan" },
      { name: "Easter Monday", date: "04-01", type: "public", localName: "Velikonočni ponedeljek" },
      { name: "Uprising Day", date: "04-27", type: "public", localName: "Dan upora" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Praznik dela" },
      { name: "Whit Sunday", date: "05-19", type: "public", localName: "Binkošti" },
      { name: "Statehood Day", date: "06-25", type: "public", localName: "Dan državnosti" },
      { name: "Assumption Day", date: "08-15", type: "public", localName: "Marijino vnebovzetje" },
      { name: "Reformation Day", date: "10-31", type: "public", localName: "Dan reformacije" },
      { name: "All Saints' Day", date: "11-01", type: "public", localName: "Dan spomina na mrtve" },
      { name: "Christmas Day", date: "12-25", type: "public", localName: "Božič" },
      { name: "Independence Day", date: "12-26", type: "public", localName: "Dan samostojnosti" },
    ],
  },
  {
    countryCode: "RS",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public", localName: "Nova godina" },
      { name: "Orthodox Christmas", date: "01-07", type: "public", localName: "Božić" },
      { name: "Statehood Day", date: "02-15", type: "public", localName: "Dan državnosti" },
      { name: "Good Friday", date: "05-03", type: "public", localName: "Veliki petak" },
      { name: "Easter Monday", date: "05-06", type: "public", localName: "Vaskrsni ponedeljak" },
      { name: "Labour Day", date: "05-01", type: "public", localName: "Praznik rada" },
      { name: "Armistice Day", date: "11-11", type: "public", localName: "Dan primirja" },
    ],
  },
  {
    countryCode: "CY",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Epiphany", date: "01-06", type: "public" },
      { name: "Clean Monday", date: "03-18", type: "public" },
      { name: "Greek Independence Day", date: "03-25", type: "public" },
      { name: "Cyprus National Day", date: "04-01", type: "public" },
      { name: "Good Friday", date: "05-03", type: "public" },
      { name: "Easter Monday", date: "05-06", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Pentecost Monday", date: "06-24", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "Independence Day", date: "10-01", type: "public" },
      { name: "Ohi Day", date: "10-28", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "MT",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "St. Paul's Shipwreck", date: "02-10", type: "public" },
      { name: "St. Joseph's Day", date: "03-19", type: "public" },
      { name: "Freedom Day", date: "03-31", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Sette Giugno", date: "06-07", type: "public" },
      { name: "St. Peter and St. Paul", date: "06-29", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "Victory Day", date: "09-08", type: "public" },
      { name: "Independence Day", date: "09-21", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Republic Day", date: "12-13", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "LU",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Europe Day", date: "05-09", type: "public" },
      { name: "Ascension Day", date: "05-09", type: "public" },
      { name: "Whit Monday", date: "05-20", type: "public" },
      { name: "National Day", date: "06-23", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "MC",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "St. Dévote", date: "01-27", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Ascension Day", date: "05-09", type: "public" },
      { name: "Whit Monday", date: "05-20", type: "public" },
      { name: "Corpus Christi", date: "05-30", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "National Day", date: "11-19", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "AL",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Summer Day", date: "03-14", type: "public" },
      { name: "Nowruz", date: "03-22", type: "public" },
      { name: "Easter Sunday", date: "03-31", type: "public" },
      { name: "Orthodox Easter", date: "05-05", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Independence Day", date: "11-28", type: "public" },
      { name: "Liberation Day", date: "11-29", type: "public" },
      { name: "National Youth Day", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "BA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Orthodox Christmas", date: "01-07", type: "public" },
      { name: "Independence Day", date: "03-01", type: "public" },
      { name: "Easter Sunday", date: "03-31", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Statehood Day", date: "11-25", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "MD",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Orthodox Christmas", date: "01-07", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Easter Sunday", date: "05-05", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Independence Day", date: "08-27", type: "public" },
      { name: "Language Day", date: "08-31", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "BY",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Orthodox Christmas", date: "01-07", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Independence Day", date: "07-03", type: "public" },
      { name: "October Revolution Day", date: "11-07", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "AD",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Epiphany", date: "01-06", type: "public" },
      { name: "Constitution Day", date: "03-14", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Whit Monday", date: "05-20", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "National Day", date: "09-08", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "LI",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Epiphany", date: "01-06", type: "public" },
      { name: "Candlemas", date: "02-02", type: "public" },
      { name: "St. Joseph's Day", date: "03-19", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Ascension Day", date: "05-09", type: "public" },
      { name: "Whit Monday", date: "05-20", type: "public" },
      { name: "Corpus Christi", date: "05-30", type: "public" },
      { name: "National Day", date: "08-15", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "SM",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Epiphany", date: "01-06", type: "public" },
      { name: "St. Agatha", date: "02-05", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Corpus Christi", date: "05-30", type: "public" },
      { name: "Liberation Day", date: "07-28", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "St. Marinus Day", date: "09-03", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "QA",
    holidays: [
      { name: "National Sports Day", date: "02-13", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "National Day", date: "12-18", type: "public" },
    ],
  },
  {
    countryCode: "KW",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "National Day", date: "02-25", type: "public" },
      { name: "Liberation Day", date: "02-26", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
    ],
  },
  {
    countryCode: "BH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Ashura", date: "07-17", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "National Day", date: "12-16", type: "public" },
    ],
  },
  {
    countryCode: "OM",
    holidays: [
      { name: "Isra and Miraj", date: "02-08", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "National Day", date: "11-18", type: "public" },
    ],
  },
  {
    countryCode: "JO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Independence Day", date: "05-25", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "IR",
    holidays: [
      { name: "Nowruz", date: "03-21", type: "public" },
      { name: "Islamic Republic Day", date: "04-01", type: "public" },
      { name: "Sizdah Bedar", date: "04-02", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Ashura", date: "07-17", type: "public" },
      { name: "Arbaeen", date: "08-26", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
    ],
  },
  {
    countryCode: "IQ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Army Day", date: "01-06", type: "public" },
      { name: "Nowruz", date: "03-21", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Republic Day", date: "07-14", type: "public" },
      { name: "Ashura", date: "07-17", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Independence Day", date: "10-03", type: "public" },
    ],
  },
  {
    countryCode: "LB",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "St. Maroun Day", date: "02-09", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Independence Day", date: "11-22", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "KH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Victory Day", date: "01-07", type: "public" },
      { name: "Khmer New Year", date: "04-14", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "King's Birthday", date: "05-14", type: "public" },
      { name: "Visak Bochea", date: "05-22", type: "public" },
      { name: "Constitution Day", date: "09-24", type: "public" },
      { name: "Pchum Ben", date: "10-01", type: "public" },
      { name: "Independence Day", date: "11-09", type: "public" },
      { name: "Water Festival", date: "11-14", type: "public" },
    ],
  },
  {
    countryCode: "MM",
    holidays: [
      { name: "Independence Day", date: "01-04", type: "public" },
      { name: "Union Day", date: "02-12", type: "public" },
      { name: "Peasants' Day", date: "03-02", type: "public" },
      { name: "Thingyan Festival", date: "04-13", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Martyrs' Day", date: "07-19", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "MN",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Tsagaan Sar", date: "02-10", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Naadam Festival", date: "07-11", type: "public" },
      { name: "Independence Day", date: "11-26", type: "public" },
    ],
  },
  {
    countryCode: "KZ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Nauryz", date: "03-21", type: "public" },
      { name: "Unity Day", date: "05-01", type: "public" },
      { name: "Defender Day", date: "05-07", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Constitution Day", date: "08-30", type: "public" },
      { name: "Independence Day", date: "12-16", type: "public" },
    ],
  },
  {
    countryCode: "GE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Orthodox Christmas", date: "01-07", type: "public" },
      { name: "Epiphany", date: "01-19", type: "public" },
      { name: "Mother's Day", date: "03-03", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Independence Restoration", date: "04-09", type: "public" },
      { name: "Orthodox Easter", date: "05-05", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Independence Day", date: "05-26", type: "public" },
      { name: "Assumption Day", date: "08-28", type: "public" },
      { name: "Svetitskhovloba", date: "10-14", type: "public" },
      { name: "St. George's Day", date: "11-23", type: "public" },
    ],
  },
  {
    countryCode: "AM",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Orthodox Christmas", date: "01-06", type: "public" },
      { name: "Army Day", date: "01-28", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Genocide Remembrance", date: "04-24", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Republic Day", date: "05-28", type: "public" },
      { name: "Constitution Day", date: "07-05", type: "public" },
      { name: "Independence Day", date: "09-21", type: "public" },
    ],
  },
  {
    countryCode: "AZ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Martyrs' Day", date: "01-20", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Novruz", date: "03-21", type: "public" },
      { name: "Victory Day", date: "05-09", type: "public" },
      { name: "Republic Day", date: "05-28", type: "public" },
      { name: "Salvation Day", date: "06-15", type: "public" },
      { name: "Armed Forces Day", date: "06-26", type: "public" },
      { name: "Independence Day", date: "10-18", type: "public" },
      { name: "Flag Day", date: "11-09", type: "public" },
      { name: "Solidarity Day", date: "12-31", type: "public" },
    ],
  },
  {
    countryCode: "MA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Independence Manifesto", date: "01-11", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Throne Day", date: "07-30", type: "public" },
      { name: "Revolution Day", date: "08-20", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Green March Day", date: "11-06", type: "public" },
      { name: "Independence Day", date: "11-18", type: "public" },
    ],
  },
  {
    countryCode: "TN",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Revolution Day", date: "01-14", type: "public" },
      { name: "Independence Day", date: "03-20", type: "public" },
      { name: "Martyrs' Day", date: "04-09", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Republic Day", date: "07-25", type: "public" },
      { name: "Islamic New Year", date: "07-07", type: "public" },
      { name: "Women's Day", date: "08-13", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Evacuation Day", date: "10-15", type: "public" },
    ],
  },
  {
    countryCode: "ET",
    holidays: [
      { name: "Christmas", date: "01-07", type: "public" },
      { name: "Epiphany", date: "01-19", type: "public" },
      { name: "Victory of Adwa", date: "03-02", type: "public" },
      { name: "Good Friday", date: "05-03", type: "public" },
      { name: "Easter", date: "05-05", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "New Year", date: "09-11", type: "public" },
      { name: "Meskel", date: "09-27", type: "public" },
    ],
  },
  {
    countryCode: "GH",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Constitution Day", date: "01-07", type: "public" },
      { name: "Independence Day", date: "03-06", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "May Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Founders' Day", date: "08-04", type: "public" },
      { name: "Kwame Nkrumah Day", date: "09-21", type: "public" },
      { name: "Farmers' Day", date: "12-06", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "TZ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Zanzibar Revolution", date: "01-12", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Union Day", date: "04-26", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Saba Saba", date: "07-07", type: "public" },
      { name: "Farmers' Day", date: "08-08", type: "public" },
      { name: "Nyerere Day", date: "10-14", type: "public" },
      { name: "Independence Day", date: "12-09", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "UG",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "NRM Liberation Day", date: "01-26", type: "public" },
      { name: "Women's Day", date: "03-08", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Martyr's Day", date: "06-03", type: "public" },
      { name: "Heroes Day", date: "06-09", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Independence Day", date: "10-09", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "RW",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Heroes Day", date: "02-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Genocide Memorial", date: "04-07", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Eid al-Adha", date: "06-17", type: "public" },
      { name: "Independence Day", date: "07-01", type: "public" },
      { name: "Liberation Day", date: "07-04", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "MU",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Abolition of Slavery", date: "02-01", type: "public" },
      { name: "Maha Shivaratri", date: "02-26", type: "public" },
      { name: "National Day", date: "03-12", type: "public" },
      { name: "Ougadi", date: "04-09", type: "public" },
      { name: "Eid al-Fitr", date: "04-10", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "Ganesh Chaturthi", date: "09-07", type: "public" },
      { name: "Arrival of Labourers", date: "11-02", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "SC",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Corpus Christi", date: "05-30", type: "public" },
      { name: "Constitution Day", date: "06-18", type: "public" },
      { name: "National Day", date: "06-29", type: "public" },
      { name: "Assumption Day", date: "08-15", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Immaculate Conception", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "CR",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "St. Joseph's Day", date: "03-19", type: "public" },
      { name: "Maundy Thursday", date: "03-28", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Juan Santamaría", date: "04-11", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Annexation of Guanacaste", date: "07-25", type: "public" },
      { name: "Our Lady of Angels", date: "08-02", type: "public" },
      { name: "Mother's Day", date: "08-15", type: "public" },
      { name: "Independence Day", date: "09-15", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "PA",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Martyrs' Day", date: "01-09", type: "public" },
      { name: "Carnival", date: "02-12", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Independence from Colombia", date: "11-03", type: "public" },
      { name: "Flag Day", date: "11-04", type: "public" },
      { name: "Independence Day", date: "11-28", type: "public" },
      { name: "Mother's Day", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "CU",
    holidays: [
      { name: "Liberation Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Revolution Day", date: "07-26", type: "public" },
      { name: "Independence Day", date: "10-10", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "DO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Epiphany", date: "01-06", type: "public" },
      { name: "Our Lady of Altagracia", date: "01-21", type: "public" },
      { name: "Duarte Day", date: "01-26", type: "public" },
      { name: "Independence Day", date: "02-27", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Restoration Day", date: "08-16", type: "public" },
      { name: "Our Lady of Mercedes", date: "09-24", type: "public" },
      { name: "Constitution Day", date: "11-06", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "JM",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Ash Wednesday", date: "02-14", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Labour Day", date: "05-23", type: "public" },
      { name: "Emancipation Day", date: "08-01", type: "public" },
      { name: "Independence Day", date: "08-06", type: "public" },
      { name: "National Heroes Day", date: "10-21", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
  {
    countryCode: "EC",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Carnival", date: "02-12", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Battle of Pichincha", date: "05-24", type: "public" },
      { name: "Independence Day", date: "08-10", type: "public" },
      { name: "Guayaquil Independence", date: "10-09", type: "public" },
      { name: "All Souls' Day", date: "11-02", type: "public" },
      { name: "Cuenca Independence", date: "11-03", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "UY",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Carnival", date: "02-12", type: "public" },
      { name: "Maundy Thursday", date: "03-28", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Landing of the 33", date: "04-19", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Battle of Las Piedras", date: "05-18", type: "public" },
      { name: "Artigas Day", date: "06-19", type: "public" },
      { name: "Constitution Day", date: "07-18", type: "public" },
      { name: "Independence Day", date: "08-25", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "VE",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Carnival", date: "02-12", type: "public" },
      { name: "Maundy Thursday", date: "03-28", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Declaration of Independence", date: "04-19", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Battle of Carabobo", date: "06-24", type: "public" },
      { name: "Independence Day", date: "07-05", type: "public" },
      { name: "Bolívar's Birthday", date: "07-24", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "BO",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Plurinational Day", date: "01-22", type: "public" },
      { name: "Carnival", date: "02-12", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Corpus Christi", date: "05-30", type: "public" },
      { name: "Aymara New Year", date: "06-21", type: "public" },
      { name: "Independence Day", date: "08-06", type: "public" },
      { name: "All Saints' Day", date: "11-01", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "PY",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Heroes' Day", date: "03-01", type: "public" },
      { name: "Maundy Thursday", date: "03-28", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Labour Day", date: "05-01", type: "public" },
      { name: "Independence Day", date: "05-14", type: "public" },
      { name: "Peace of Chaco", date: "06-12", type: "public" },
      { name: "Founding of Asunción", date: "08-15", type: "public" },
      { name: "Virgin of Caacupé", date: "12-08", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
    ],
  },
  {
    countryCode: "FJ",
    holidays: [
      { name: "New Year's Day", date: "01-01", type: "public" },
      { name: "Good Friday", date: "03-29", type: "public" },
      { name: "Easter Monday", date: "04-01", type: "public" },
      { name: "Fiji Day", date: "10-10", type: "public" },
      { name: "Diwali", date: "10-31", type: "public" },
      { name: "Prophet's Birthday", date: "09-15", type: "public" },
      { name: "Christmas Day", date: "12-25", type: "public" },
      { name: "Boxing Day", date: "12-26", type: "public" },
    ],
  },
];

async function main() {
  console.log("🎉 Seeding public holidays to Turso...");

  for (const countryData of holidaysData) {
    const country = await prisma.country.findUnique({
      where: { code: countryData.countryCode },
    });

    if (!country) {
      console.log(`⚠️  Country not found: ${countryData.countryCode}`);
      continue;
    }

    console.log(`📅 Adding ${countryData.holidays.length} holidays for ${country.name}...`);

    for (const holiday of countryData.holidays) {
      await prisma.publicHoliday.upsert({
        where: {
          countryId_name_date: {
            countryId: country.id,
            name: holiday.name,
            date: holiday.date,
          },
        },
        update: {
          localName: holiday.localName,
          type: holiday.type,
          description: holiday.description,
        },
        create: {
          countryId: country.id,
          name: holiday.name,
          localName: holiday.localName,
          date: holiday.date,
          type: holiday.type || "public",
          isRecurring: true,
          description: holiday.description,
        },
      });
    }

    console.log(`✅ Added ${countryData.holidays.length} holidays for ${country.name}`);
  }

  console.log("🎉 Turso holidays seed completed!");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding holidays to Turso:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
